### ISSUE TITLE
VLA ms to matlab format

### ISSUE THREAD

**Issue by infinitron** [basp-group/SARA-adaptive-PPD#1]
Hi there,

Is there any script to convert the VLA MS file into the format that is readable by the ppd program? The Cyg A output from this program is really promising and I would like to try it on a few other datasets. Any help in this regard would be highly appreciated.

Thanks,
Karthik

**Comment by arwina** [comment]
Hi, we use Meqtrees (python packages) to read MSs. Then using Pyxis, we extract the columns we are interested in (DATA, UVW, TIME, WEIGHTS,FLAG,ANTENNA1 ANTENNA2) and save the arrays in a mat file 
you can download Meqtrees here https://github.com/ska-sa/meqtrees/wiki/Installation.
I hope this is helpful.

**Comment by infinitron** [comment]
Thanks for the instructions @arwina.
Now, when I'm executing the program for the default data (3c391_I00.mat), I'm getting the following error

```
Using real data ... 


 Time information needed for data blocking!
INFO: Imaging up to 2.644x the nominal resolution
Block size should be in [17820 22220]

INFO: Data slice sz 68699
INFO:No time scans identified
--> splitting by equal nbr of snapshotsArray indices must be positive integers or logical values.

Error in util_time_based_block_sp_ar (line 87)
            scanStartingSnap(end) = scanStartingSnap(end) + mod(snapshotsNbr,approxBlkNbr);% add remaining snapshots to last scan

Error in script_get_real_data_build_operators (line 27)
            blockStruct =util_time_based_block_sp_ar(time,param_block);

Error in main_script_imaging_real_data (line 65)
script_get_real_data_build_operators
 ````
The 3c391_I00.mat file is missing the TIME column. Is this error because of that?
The data from the 3C391 tutorial has only one spectral window. Should the visibilities be averaged if there are multiple spectral windows in the observation?

**Comment by arwina** [comment]
Thanks for pointing this out. The mat file does not contain the time info used for splitting. I ve just uploaded the correct data file.
The data from 3C391 MS does indeed contain 1 spectral window yet multiple fields. The extracted data herein corresponds to field Id 0 and the first freq. channel. In our test we do not apply further averaging. 
Please note that the used calibrated measurement set can be found here https://casa.nrao.edu/Data/EVLA/3C391/EVLA_3C391_FinalCalibratedMosaicMS.tgz

**Comment by infinitron** [comment]
Sorry to bother you again. But I'm getting the following error with the new data now
<pre>
Using real data ... 

INFO: Imaging up to 2.644x the nominal resolution
Block size should be in [17820 22220]

INFO: Data slice sz 68699
INFO: 12 Time scans detected--> Initial blocking based on scans
INFO: average scan size is 5724 --> attempt to merge--> successful!
 2 Blocks, size stats: mean 34349, std 13060, min 25114, max 43585
Average block size: 34349 
Desired block size: 20000
Smallest block size: 25114
Largest block size: 43585
Initializing the NUFFT operator


Computing block matrices ...
Error using op_nufft (line 25)
<b>fatrix2 has some very weird bugs with subindexing; force st.p to be a (sparse) matrix</b>
Error in op_p_nufft (line 101)
            [~, ~, Gb, ~] = op_nufft([p{q, 1} p{q, 2}], N, Nn, No, Ns);
Error in script_get_real_data_build_operators (line 39)
        [A, At, T, W, Gw] = op_p_nufft([v u], [Ny Nx], [Ky Kx], [oy*Ny ox*Nx], [Ny/2 Nx/2], nW);
Error in main_script_imaging_real_data (line 69)
script_get_real_data_build_operators 
</pre>

**Comment by arwina** [comment]
Hi, this is due to some precision problem in matlab.
Please comment the following line (294) in ./irt/nufft/nufft_init.m
% sparse object, to better handle single precision operations!
st.p = Gsparse(st.p, 'odim', [M 1], 'idim', [prod(Kd) 1]);

**Comment by infinitron** [comment]
Hi, I've commented that line and the error went away. Matlab started to throw an error in __so_fft2_adj.m__ (line 18). because there was a mismatch in the size of ```X``` and the size supplied by ```No``` to reshape. I've padded ```X``` with extra zeros to the number elements ```(No(1)*No(0))```.
```
sx = size(X);
totalElements = No(1)*No(2);
if sx(1)~=totalElements 
    X = padarray(X,[totalElements-sx(1),0],0,'post');
end
X = reshape(X, No);
```
 Now the following error pops up
<pre>
.
.
.
.
*****************************************
**  DWT Extension Mode: Periodization  **
*****************************************
                                         
Computing operator norms ...
Natural W ...
Norm = 4.671811e+08 

Preconditioning ...
Norm = 5.346704e+06 

Iteration 1:
Error using  * 
<b>Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of rows in the
second matrix. To perform elementwise multiplication, use '.*'.

Error in main_script_imaging_real_data>@(x)T{i}*A(x)</b>

Error in solver_fb_nnls (line 83)
    res = A(grad);

Error in main_script_imaging_real_data (line 84)
[result_nnls.sol{i}, result_nnls.L2_v{i}] = solver_fb_nnls(y{i}, @(x) T{i} * A(x),@(x) At((T{i})' * x),param_nnls);
</pre>

**Comment by arwina** [comment]
In so_fft2_adj.m (line 18), what are the obtained dim of X and the expected ones?
Which matlab version you re using ?

**Comment by infinitron** [comment]
The program throws an error with the following sizes
size(x) = 25809           1
size(No) = 1024        1024

I'm using 2018b at the moment. But, I can try running it in other versions as well.

**Comment by arwina** [comment]
It seems that you re applying the operator **At** on a vector of the same size as the data block instead of **No**.

If you have modified the main script please post your version here.

**Comment by infinitron** [comment]
I did not modify the main script. In fact, I just re-downloaded the main script file and ran it. It is still giving me the aforementioned error

**Comment by arwina** [comment]
Ok thanks. I have uploaded a new function **op_p_nufft_up.m** to be used instead of **op_p_nufft.m** from the toolbox  **ppd-for-ri** . The problem should be fixed now.

**Comment by infinitron** [comment]
Thanks a lot. It's working now!
